// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfI1pviQkUfEFQ75O59FyqcYe3Z3LLfcA',
    appId: '1:513890990999:web:5a4b81cf0c78fd349b22d2',
    messagingSenderId: '513890990999',
    projectId: 'satu-salingbantu',
    authDomain: 'satu-salingbantu.firebaseapp.com',
    storageBucket: 'satu-salingbantu.appspot.com',
    measurementId: 'G-2S7GGENRE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJsODpajfOfMp8y6IGEaYIeuHBSG2Gi4w',
    appId: '1:513890990999:android:160f1dd5500faafe9b22d2',
    messagingSenderId: '513890990999',
    projectId: 'satu-salingbantu',
    storageBucket: 'satu-salingbantu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnkP6wpWO-lvNoTEVTbS--vdH3osiQ5kk',
    appId: '1:513890990999:ios:7beef3fee85076389b22d2',
    messagingSenderId: '513890990999',
    projectId: 'satu-salingbantu',
    storageBucket: 'satu-salingbantu.appspot.com',
    iosClientId: '513890990999-6jre5ful0cjgu64jft7jjd0er1uvic6b.apps.googleusercontent.com',
    iosBundleId: 'id.satu.salingbantu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnkP6wpWO-lvNoTEVTbS--vdH3osiQ5kk',
    appId: '1:513890990999:ios:7beef3fee85076389b22d2',
    messagingSenderId: '513890990999',
    projectId: 'satu-salingbantu',
    storageBucket: 'satu-salingbantu.appspot.com',
    iosClientId: '513890990999-6jre5ful0cjgu64jft7jjd0er1uvic6b.apps.googleusercontent.com',
    iosBundleId: 'id.satu.salingbantu',
  );
}
